### PR TITLE
Review the codes and merge to the master.

### PR DESCRIPTION
**Pull request by fae713**
Review the backend codes and then merge them to the master

### CODE REVIEW

**Review by NwoguGlory1 — APPROVED** [review]
Reviewed & Merged!

**Comment by NwoguGlory1** [comment]
pls check now. I have merged it

**Comment by NwoguGlory1** [comment]
well done Fae. I see the project has been reviewed and you edited
the google doc. I should be able to upload a screenshot when I get to the
hub tomorrow.

**Comment by fae713** [comment]
Alright dear

**Pull request merged**
